class TradeGen4:
    GIVE = ['Caterpie', 'Weedle', 'Pidgey', 'Rattata', 'Alolan Rattata',  'Spearow', 'Ekans', 'Alolan Raichu', 'Sandshrew', 'Alolan Sandshrew', 'Nidoran♀', 'Nidoran♂', 'Vulpix',
               'Alolan Vulpix', 'Jugglypuff', 'Oddish', 'Paras', 'Venonat', 'Diglett', 'Meowth', 'Mankey', 'Growlithe', 'Poliwag', 'Bellsprout', 'Tentacool', 'Alolan Geodude',
               'Slowpoke', 'Magnemite', 'Farfetch\'d', 'Doduo', 'Seel', 'Grimer', 'Alolan Grimer', 'Shellder', 'Gastly', 'Drowzee', 'Krabby', 'Voltorb', 'Exeggcute', 'Cubone', 
               'Alolan Marowak', 'Hitmonlee', 'Hitmonchan', 'Lickitung', 'Koffing', 'Rhyhorn', 'Tangela', 'Kangaskhan', 'Horsea', 'Staryu', 'Mr. Mime', 'Scyther', 'Jynx', 
               'Electabuzz', 'Magmar', 'Pinsir', 'Tauros', 'Lapras', 'Eevee', 'Snorlax', 'Sentret', 'Hoothott', 'Ledyba', 'Spinarak', 'Chinchou', 'Togepi', 'Natu', 'Mareep', 
               'Marill', 'Sudowoodo', 'Hoppip', 'Sunkern', 'Yanma', 'Wooper', 'Wobbuffet', 'Girafarig', 'Pineco', 'Dunsparce', 'Gligar', 'Snubull', 'Qwilfish', 'Shuckle', 
               'Sneasel', 'Teddiursa', 'Slugma', 'Swinub', 'Corsola', 'Remoraid', 'Mantine', 'Skarmory', 'Houndour', 'Phanpy', 'Stantler', 'Smeargle', 'Tyrogue', 'Hitmontop', 
               'Miltank', 'Poochyena', 'Zigzagoon', 'Lotad', 'Seedot', 'Tailow', 'Wingull', 'Ralts', 'Surskit', 'Shroomish', 'Slakoth', 'Nincada', 'Whismur', 'Makuhita', 
               'Nosepass', 'Skitty', 'Sableye', 'Mawile', 'Aron', 'Electrike', 'Plusle', 'Minun', 'Volbeat', 'Gulpin', 'Carvana', 'Wailmer', 'Numel', 'Torkoal', 'Spoink', 
               'Spinda', 'Trapinch', 'Vibrava', 'Cacnea', 'Swablu', 'Zangoose', 'Seviper', 'Lunatone', 'Solrock', 'Corphish', 'Baltoy', 'Feebas', 'Castform', 'Shuppet', 
               'Duskull', 'Tropius', 'Absol', 'Snorunt', 'Spheal', 'Clampearl', 'Huntail', 'Relicanth', 'Bagon', 'Patrat', 'Lillipup', 'Purrloin', 'Pansage', 'Pansear', 
               'Panpour', 'Munna', 'Pidove', 'Blitzle', 'Roggenrola', 'Woobat', 'Drilbur', 'Audino', 'Timburr', 'Tympole', 'Throh', 'Sawk', 'Sewaddle', 'Venipede', 'Cottonee', 
               'Petilil', 'Basculin', 'Sandile', 'Darumaka', 'Maractus', 'Dwebble', 'Scraggy', 'Sigilyph', 'Yamask', 'Trubbish', 'Zorua', 'Tirtouga', 'Archen', 'Minccino', 
               'Gothita', 'Solosis', 'Ducklett', 'Vanillite', 'Deerling', 'Emolga', 'Karrablast', 'Foongus', 'Frillish', 'Alomomola', 'Joltik', 'Ferroseed', 'Klink', 'Tynamo', 
               'Elgyem', 'Litwick', 'Axew', 'Cubchoo', 'Cryogonal', 'Shelmet', 'Stunkfisk', 'Mienfoo', 'Druddigon', 'Golett', 'Pawniard', 'Booffalant', 'Rufflet', 'Vullaby', 
               'Heatmor', 'Durant', 'Deino', 'Larvesta', 'Chespin', 'Fennekin', 'Froakie', 'Bunnelby', 'Fletchling', 'Scatterbug', 'Litleo', 'Skiddo', 'Pancham', 'Espurr', 'Honedge', 
               'Spritzee', 'Swirlix', 'Inkay', 'Binacle', 'Skrelp', 'Clauncher', 'Helioptile', 'Tyrunt', 'Amaura', 'Sylveon', 'Hawlucha', 'Dedenne', 'Carbink', 'Goomy', 
               'Klefki', 'Phantump', 'Bergmite', 'Rowlet', 'Litten', 'Popplio', 'Pikipek', 'Yungoos', 'Grubbin', 'Crabrawler', 'Oricorio', 'Cutiefly', 'Rockruff', 'Wishiwashi', 
               'Mareanie', 'Dewpider', 'Morelull', 'Salandit', 'Stufful', 'Bounsweet', 'Oranguru', 'Passimian', 'Wimpod', 'Sandygast', 'Komala', 'Mimikyu', 'Drampa', 'Dhelmise', 
               'Jangmo-o']

    REQUEST = ['Turtwig', 'Chimchar', 'Piplup', 'Starly', 'Bidoof', 'Kricketot', 'Shinx', 'Abra', 'Magikarp', 'Budew', 'Zubat', 'Geodude', 'Onix', 'Cranidos', 'Shieldon', 
                        'Machop', 'Psyduck', 'Brumy', 'Wurmple', 'Silcoon', 'Cascoon', 'Combee', 'Pachirisu', 'Buizel', 'Cherubi', 'Shellos', 'Heracross', 'Aipom', 'Drifloon', 
                        'Buneary', 'Gastly', 'Mismagius', 'Murkrow', 'Glamoew', 'Goldeen', 'Barboach', 'Chingling', 'Stunky', 'Meditite', 'Bronzor', 'Ponyta', 'Bonsly', 'Chansey', 
                        'Mr. Mime', 'Clefairy', 'Chatot', 'Pikachu', 'Hoothoot', 'Spiritomb', 'Gible', 'Snorlax', 'Riolu', 'Wooper', 'Wingull', 'Girafarig', 'Hippopotas', 'Marill', 
                        'Sporupi', 'Croagunk', 'Carnivine', 'Remoraid', 'Finneon', 'Tentacool', 'Feebas', 'Mantyke', 'Snover', 'Sneasel', 'Gligar', 'Nosepass', 'Ralts', 'Lickitung', 
                        'Eevee', 'Swablu', 'Togepi', 'Houndour', 'Magnemite', 'Tangela', 'Yanma', 'Tropius', 'Rhyhorn', 'Duskull', 'Porygon', 'Scyther', 'Elekid', 'Magby', 'Swinub',
                        'Absol']